services:
  wem.geodata.vent_listener.sitemap_listener:
    class: WEM\GeoDataBundle\EventListener\SitemapListener
    tags:
        - { name: kernel.event_listener, event: contao.sitemap }
    public: true