services:
  wem.geodata.listener.sitemap_listener:
    class: WEM\GeoDataBundle\EventListener\SitemapListener
    tags:
        - { name: kernel.event_listener, event: contao.sitemap }
    public: true

  wem.geodata.listener.generate_breadcrumb_listener:
    class: WEM\GeoDataBundle\EventListener\GenerateBreadcrumbListener
    public: true
  wem.geodata.listener.replace_insert_tags_listener:
    class: WEM\GeoDataBundle\EventListener\ReplaceInsertTagsListener
    public: true


