services:
    WEM\GeoDataBundle\Migration\M202307170826_MultiCategories:
        arguments:
            $connection: '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    WEM\GeoDataBundle\Migration\M202307181508_DefaultMapCategory:
        arguments:
            $connection: '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    WEM\GeoDataBundle\Migration\M202410251433_EncodeMapProviderGmapKey:
        arguments:
            $connection: '@database_connection'
            $encryption: '@wem.encryption_util'
        tags:
            - { name: contao.migration, priority: 0 }